complete rewrite of startvm

diff --git a/image/base/startvm b/image/base/startvm
--- a/image/base/startvm
+++ b/image/base/startvm
@@ -1,210 +1,84 @@
 #!/bin/bash
 
-set -x
+# This entrypoint for KVM container configures and attaches network bridges to
+# the VM and starts KVM with the selected options.
 
-atoi()
-{
-	#Returns the integer representation of an IP arg, passed in ascii dotted-decimal notation (x.x.x.x)
-	IP=$1; IPNUM=0
-	for (( i=0 ; i<4 ; ++i )); do
-	((IPNUM+=${IP%%.*}*$((256**$((3-${i}))))))
-	IP=${IP#*.}
-	done
-	echo $IPNUM
+# See Dockerfile reference and README.md for further info.
+
+# If no arguments, the VM will lauch with 4 cores and 1GB of memory
+
+: ${DEBUG:='N'}
+: ${LAUNCHER:='qemu-system-x86_64'}
+: ${DNSMASQ_CONF_DIR:='/etc/dnsmasq.d'}
+: ${DNSMASQ:='/usr/sbin/dnsmasq'}
+: ${QEMU_CONF_DIR:='/etc/qemu-kvm'}
+
+: ${KVM_BLK_OPTS:="-drive if=virtio,file=/image/image"}
+
+: ${KVM_OPTS:="\
+  -nodefaults \
+  -device virtio-balloon-pci,id=balloon0 \
+  -realtime mlock=off \
+  -msg timestamp=on \
+  -chardev pty,id=charserial0 \
+  -device isa-serial,chardev=charserial0,id=serial0 \
+  -serial stdio \
+  "}
+
+: ${KVM_CPU_OPTS:="-m 1024 -smp 4,sockets=4,cores=1,threads=1"}
+
+log () {
+  case "$1" in
+    INFO | WARNING | ERROR )
+      echo "$1: ${@:2}"
+      ;;
+    DEBUG)
+      [[ $DEBUG -eq 1 ]] && echo "$1: ${@:2}"
+      ;;
+    *)
+      echo "-- $@"
+      ;;
+  esac
 }
 
-itoa()
-{
-	#returns the dotted-decimal ascii form of an IP arg passed in integer format
-	echo -n $(($(($(($((${1}/256))/256))/256))%256)).
-	echo -n $(($(($((${1}/256))/256))%256)).
-	echo -n $(($((${1}/256))%256)).
-	echo $((${1}%256))
+# ContainsElement: checks if first parameter is among the array given as second parameter
+# returns 0 if the element is found in the list and 1 if not
+# usage: containsElement $item $list
+
+containsElement () {
+  local e
+  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
+  return 1
 }
 
-fetch_rancher()
-{
-	name=$1
-	file=$2
-
-	curl -s http://169.254.169.250/2015-07-25/self/container/labels/$name > $file
-	if [ $? -ne 0 ]
-	then
-		return
-	fi
-	content=`cat $file`
-	if [[ $content == "Not found"* ]]
-	then
-		return
-	fi
-	echo $file
-	return
+# Generate random MAC address
+genMAC () {
+  hexchars="0123456789ABCDEF"
+  end=$( for i in {1..8} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/:\1/g' )
+  echo "FE:05$end"
 }
 
-fetch_metadata()
-{
-	fetch_rancher io.rancher.vm.metadata metadata.rancher
-	return
+# atoi: Returns the integer representation of an IP arg, passed in ascii
+# dotted-decimal notation (x.x.x.x)
+atoi() {
+  IP=$1
+  IPnum=0
+  for (( i=0 ; i<4 ; ++i ))
+  do
+    ((IPnum+=${IP%%.*}*$((256**$((3-${i}))))))
+    IP=${IP#*.}
+  done
+  echo $IPnum
 }
 
-fetch_os_metadata()
-{
-	fetch_rancher io.rancher.vm.os_metadata os_metadata.rancher
-	return
+# itoa: returns the dotted-decimal ascii form of an IP arg passed in integer
+# format
+itoa() {
+  echo -n $(($(($(($((${1}/256))/256))/256))%256)).
+  echo -n $(($(($((${1}/256))/256))%256)).
+  echo -n $(($((${1}/256))%256)).
+  echo $((${1}%256))
 }
-
-fetch_userdata()
-{
-	fetch_rancher io.rancher.vm.userdata userdata.rancher
-	return
-}
-
-wait_for_metadata()
-{
-    counter=0
-    printf 'Waiting for metadata'
-    until $(curl --output /dev/null --silent --head --fail http://rancher-metadata/latest/self/container); do
-        printf '.'
-        sleep 1
-        counter=$((counter + 1))
-        if [ "$counter" -gt 30 ]; then
-            echo
-            echo "Could not reach metadata." >&2
-            exit 1
-        fi
-    done
-    echo
-}
-
-generate_cloud_drive()
-{
-    # get metadata and create cloud drive v2 for cloud-init
-	os_metadata=`fetch_os_metadata`
-	if [ ! -f $os_metadata ]
-	then
-		os_metadata=""
-	fi
-	metadata=`fetch_metadata`
-	if [ ! -f $metadata ]
-	then
-		metadata=""
-	fi
-	userdata=`fetch_userdata`
-	if [ ! -f $userdata ]
-	then
-		userdata=""
-	fi
-
-	if [ "$metadata" == "" -a "$userdata" == "" -a "$os_metadata" == "" ]
-	then
-		return
-	fi
-	TMPDIR=`mktemp -d -t ranchervm.XXXXXX`
-	if [ $? -ne 0 ]
-	then
-		echo Fail to create temporaily directory
-		exit 1
-	fi
-
-	dirs=("/openstack/2012-08-10/" "/openstack/latest/" \
-	      "/ec2/2009-04-04/" "/ec2/latest/")
-	for i in ${dirs[@]}
-	do
-		dir=$TMPDIR$i
-		metadatasrc=$metadata
-		metafile=$dir"meta_data.json"
-		userfile=$dir"user_data"
-		if [[ $i == "/openstack"* ]]
-		then
-			metadatasrc=$os_metadata
-		fi
-		mkdir -p $dir
-		if [[ -e "$metadatasrc" ]]
-		then
-			cp $metadatasrc $metafile
-		fi
-		if [[ -e "$userdata" ]]
-		then
-			cp $userdata $userfile
-		fi
-	done
-	iso="cloud-drive.iso"
-	genisoimage -allow-lowercase -allow-multidot -J -l -ldots -o $iso \
-		    -publisher Rancher -quiet -r -V config-2 $TMPDIR
-	if [ $? -ne 0 ]
-	then
-		echo Fail to create cloud-drive ISO image for cloud-init
-		exit 1
-	fi
-	echo $iso
-}
-
-# These two variables can be overwritten
-
-: ${KVM_BLK_OPTS:="-drive file=\$KVM_IMAGE,if=none,id=drive-disk0,format=qcow2 \
--device virtio-blk-pci,scsi=off,drive=drive-disk0,id=virtio-disk0,bootindex=1"}
-: ${KVM_RAW_BLK_OPTS:="-drive file=\$KVM_IMAGE,if=none,id=drive-disk0,format=raw \
--device virtio-blk-pci,scsi=off,drive=drive-disk0,id=virtio-disk0,bootindex=1"}
-: ${KVM_NET_OPTS:="-netdev bridge,br=\$BRIDGE_IFACE,id=net0 \
--device virtio-net-pci,netdev=net0,mac=\$MAC"}
-
-# For debugging
-if [ "$1" = "bash" ]; then
-  exec bash
-fi
-
-# Pass Docker command args to kvm
-KVM_ARGS=$@
-
-# Create the qcow disk image on the Docker volume named /image, using
-# the compressed qcow image that came with Docker image as the base.
-# Docker volumes typically perform better than the file system for
-# Docker images (no need for overlay fs etc.)
-
-if [ -e /dev/vm/root ]; then
-    KVM_BLK_OPTS="$KVM_RAW_BLK_OPTS"
-    KVM_IMAGE=/dev/vm/root
-else
-    BASE_IMAGE_DIR_LIST=( `ls /base_image` )
-    if [ ${#BASE_IMAGE_DIR_LIST[@]} -ne 1 ]; then
-    echo "/base_image directory must contain exactly one base image file"
-    exit 1
-    fi
-
-    if [ ! -d "/image" ]; then
-    echo "/image directory does not exist, failed to mount volume /image?"
-    exit 2
-    fi
-
-    KVM_IMAGE=/image/sda.qcow2
-    if [ ! -f "$KVM_IMAGE" ]; then
-        qemu-img create -f qcow2 -b /base_image/${BASE_IMAGE_DIR_LIST[0]} \
-        $KVM_IMAGE > /dev/null
-        if [[ $? -ne 0 ]]; then
-            echo "Failed to create qcow2 image"
-            exit 3
-        fi
-    fi
-fi
-
-VOLUMES_DIR="/volumes/"
-VOLUMES_LIST=`find $VOLUMES_DIR -name "*.img" | sort -d`
-extra_kvm_blk_opts=""
-for volume in $VOLUMES_LIST /dev/vm/disk*
-do
-    if [ -e $volume ]; then
-        extra_kvm_blk_opts=$extra_kvm_blk_opts" -drive file=$volume,if=virtio,format=raw"
-    fi
-done
-KVM_BLK_OPTS=$KVM_BLK_OPTS$extra_kvm_blk_opts
-
-# Network setup:
-#
-# 1. Create a bridge named br0
-# 2. Remove IP from eth0, save eth0 MAC, give eth0 a random MAC
-
-IFACE=eth0
-BRIDGE_IFACE=br0
 
 cidr2mask() {
   local i mask=""
@@ -225,96 +99,176 @@ cidr2mask() {
   echo $mask
 }
 
-setup_tap() {
-    MAC=`ip addr show $IFACE | grep ether | sed -e 's/^[[:space:]]*//g' -e 's/[[:space:]]*\$//g' | cut -f2 -d ' '`
-    ip link set dev eth0 down
-    LAUNCHER="tapclient --"
-    KVM_NET_OPTS="-netdev tap,fd=%FD%,id=hostnet0 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=$MAC"
+# Generates and returns a new IP and MASK in a superset (inmediate wider range)
+# of the given IP/MASK
+# usage: getNonConflictingIP IP MASK
+# returns NEWIP MASK
+getNonConflictingIP () {
+    local IP="$1"
+    local CIDR="$2"
+
+    let "newCIDR=$CIDR-1"
+
+    local i=$(atoi $IP)
+    let "j=$i^(1<<(32-$CIDR))"
+    local newIP=$(itoa j)
+
+    echo $newIP $newCIDR
 }
 
-setup_bridge_networking() {
-    MAC=`ip addr show $IFACE | grep ether | sed -e 's/^[[:space:]]*//g' -e 's/[[:space:]]*\$//g' | cut -f2 -d ' '`
-    IP=`ip addr show dev $IFACE | grep "inet $IP" | awk '{print $2}' | cut -f1 -d/`
-    CIDR=`ip addr show dev $IFACE | grep "inet $IP" | awk '{print $2}' | cut -f2 -d/`
-    NETMASK=`cidr2mask $CIDR`
-    if [ "$RANCHER_NETWORK" = "true" ]
-    then
-        GATEWAY=$(curl -s http://169.254.169.250/2015-07-25/self/container/labels/io.rancher.vm.metadata | jq -r '.["local-ipv4-gateway"]')
+# generates unused, random names for macvlan or bridge devices
+# usage: generateNetDevNames DEVICETYPE
+#   DEVICETYPE must be either 'macvlan' or 'bridge'
+# returns:
+#   - bridgeXXXXXX if DEVICETYPE is 'bridge'
+#   - macvlanXXXXXX, macvtapXXXXXX if DEVICETYPE is 'macvlan'
+generateNetdevNames () {
+  devicetype=$1
+
+  local netdevinterfaces=($(ip link show | awk "/$devicetype/ { print \$2 }" | cut -d '@' -f 1 | tr -d :))
+  local randomID=$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 6 | head -n 1)
+
+  # check if the device already exists and regenerate the name if so
+  while containsElement "$devicetype$randomID" "${netdevinterfaces[@]}"; do randomID=$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 6 | head -n 1); done
+
+  echo "$randomID"
+}
+
+setupBridge () {
+  set -x
+  local iface="$1"
+  local mode="$2"
+  local deviceID=$(generateNetdevNames $mode)
+  local bridgeName="$mode$deviceID"
+
+  if [[ $mode == "bridge" ]]; then
+    brctl addbr "$bridgeName"
+    brctl addif "$bridgeName" "$iface"
+  else # use macvlan devices by default
+    vtapdev="macvtap${deviceID}"
+    until $(ip link add link $iface name $vtapdev type macvtap mode bridge); do
+      sleep 1
+    done
+
+    ip link set $vtapdev address "$MAC"
+    ip link set $vtapdev up
+
+    # create a macvlan device for the host
+    ip link add link $iface name $bridgeName type macvlan mode bridge
+    ip link set $bridgeName up
+
+    # create dev file (there is no udev in container: need to be done manually)
+    IFS=: read major minor < <(cat /sys/devices/virtual/net/$vtapdev/tap*/dev)
+    mknod "/dev/$vtapdev" c $major $minor
+  fi
+
+  set +x
+  # get a new IP for the guest machine in a broader network broadcast domain
+  if ! [[ -z $IP ]]; then
+    newIP=($(getNonConflictingIP $IP $CIDR))
+    ip address del "$IP/$CIDR" dev "$iface"
+    ip address add "${newIP[0]}/${newIP[1]}" dev "$bridgeName"
+  fi
+
+  ip link set dev "$bridgeName" up
+
+  echo $deviceID
+}
+
+# Setup macvtap device to connect later the VM and setup a new macvlan devide
+# to connect the host machine to the network
+configureNetworks () {
+  local i=0
+
+  local GATEWAY=$(ip r | grep default | awk '{print $3}')
+  local IP
+
+  for iface in "${local_ifaces[@]}"; do
+
+    IPs=$(ip address show dev $iface | grep inet | awk '/inet / { print $2 }' | cut -f1 -d/)
+    IPs=($IPs)
+    MAC=$(ip link show $iface | awk '/ether/ { print $2 }')
+    log "DEBUG" "Container original MAC address: $MAC"
+
+    # If the container has more than one IP configured in a given interface,
+    # the user can select which one to use.
+    # The SELECTED_NETWORK environment variable is used to select that IP.
+    # This env variable must be in the form IP/MASK (e.g. 1.2.3.4/24).
+    #
+    # If this env variable is not set, the IP to be given to the VM is
+    # the first in the list for that interface (default behaviour).
+
+    if ! [[ -z "$SELECTED_NETWORK" ]]; then
+      local given_ip given_mask
+      IFS=/ read given_ip given_mask <<< $SELECTED_NETWORK
+      local given_addr=$(atoi $given_ip)
+      local given_mask=$((0xffffffff << (32 - $given_mask) & 0xffffffff))
+      local given_broadcast=$((given_addr | ~given_mask & 0xffffffff))
+      local given_network=$((given_addr & given_mask))
+
+      for configured_ip in "${IPs[@]}"; do
+        local configured_ip=$(atoi $configured_ip)
+        if [[ $configured_ip -gt $given_network && $configured_ip -lt $given_broadcast ]]; then
+          IP=$(itoa $configured_ip)
+          log "INFO" "SELECTED_NETWORK ($SELECTED_NETWORK) found with ip $IP in $iface interface."
+        fi
+      done
+      [[ -z "$IP" ]] && log "WARNING" "SELECTED_NETWORK ($SELECTED_NETWORK) not found in $iface interface."
     else
-        GATEWAY=`ip route get 8.8.8.8 | grep via | cut -f3 -d ' '`
-    fi
-    NAMESERVER=( `grep nameserver /etc/resolv.conf | grep -v "#" | cut -f2 -d ' '` )
-    NAMESERVERS=`echo ${NAMESERVER[*]} | sed "s/ /,/"`
-
-    cat > /etc/dnsmasq.conf << EOF
-user=root
-dhcp-range=$IP,$IP
-dhcp-host=$MAC,$HOSTNAME,$IP,infinite
-dhcp-option=option:router,$GATEWAY
-dhcp-option=option:netmask,$NETMASK
-dhcp-option=option:dns-server,$NAMESERVERS
-EOF
-
-    if [ -z $NO_DHCP ]; then
-        dnsmasq
+      IP=${IPs[0]}
     fi
 
-    # Generate random new MAC address
-    hexchars="0123456789ABCDEF"
-    end=$( for i in {1..8} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/:\1/g' )
-    NEWMAC=`echo 06:FE$end`
+    local CIDR=$(ip address show dev $iface | awk "/inet $IP/ { print \$2 }" | cut -f2 -d/)
 
-    let "NEWCIDR=$CIDR-1"
-    #NEWNETMASK=`cidr2mask $NEWCIDR`
+    # use container MAC address ($MAC) for tap device
+    # and generate a new one for the local interface
+    ip link set $iface down
+    ip link set $iface address $(genMAC)
+    ip link set $iface up
 
-    i=`atoi $IP`
-    let "i=$i^(1<<$CIDR)"
-    NEWIP=`itoa i`
+    deviceID=($(setupBridge $iface "macvlan"))
+    bridgeName="macvlan$deviceID"
+    # kvm configuration:
+    let fd=$i+3
+    KVM_NET_OPTS="$KVM_NET_OPTS -netdev tap,id=net$i,vhost=on,fd=$fd ${fd}<>/dev/macvtap$deviceID"
 
-    ip link set dev $IFACE down
-    ip link set $IFACE address $NEWMAC
-    ip addr del $IP/$CIDR dev $IFACE
+    log "DEBUG" "bridgeName: $bridgeName"
+    KVM_NET_OPTS=" -device virtio-net-pci,netdev=net$i,mac=$MAC $KVM_NET_OPTS"
+    let i++
 
-    brctl addbr $BRIDGE_IFACE
-    brctl addif $BRIDGE_IFACE $IFACE
-    ip link set dev $IFACE up
-    ip link set dev $BRIDGE_IFACE up
-    if [ -z $NO_DHCP ]; then
-        ip addr add $NEWIP/$NEWCIDR dev $BRIDGE_IFACE
-    fi
-
-    if [[ $? -ne 0 ]]; then
-        echo "Failed to bring up network bridge"
-        exit 4
-    fi
-
-    # Exec kvm as PID 1
-
-    echo allow $BRIDGE_IFACE >  /etc/qemu/bridge.conf
+  done
 }
 
-# need to wait until network is ready
-wait_for_metadata
-ISO=`generate_cloud_drive`
-if [[ $ISO ]]
-then
-	KVM_BLK_OPTS=$KVM_BLK_OPTS" -cdrom $ISO"
-fi
+# MAIN
 
-if [ "$RANCHER_NETWORK" = "true" ] && [ -e /var/run/rancher/tap.sock ]; then
-    setup_tap
+#enable KVM support onl if the host supports it
+if [[ $(grep -e vmx -e svm /proc/cpuinfo) ]]; then
+  log "INFO" "KVM acceleration enabled"
+  KVM_OPTS="$KVM_OPTS -enable-kvm -machine accel=kvm,usb=off "
 else
-    setup_bridge_networking
+  log "INFO" "KVM acceleration disabled"
+  KVM_OPTS="$KVM_OPTS -machine usb=off "
 fi
 
+case "$DEBUG" in
+  [Yy1]* ) DEBUG=1;;
+  [Nn0]* ) DEBUG=0;;
+  *      ) log "ERROR" "DEBUG incorrect or undefined. It must be one of [Yy1Nn0]"; exit 1;;
+esac
 
-# If /vm does not exist, we still proceed with running KVM. We just
-# won't get a VNC console socket.
-if [ -d /vm ]; then
-    DOCKERID=`cat /proc/self/cgroup | grep docker | awk -F/ '{print $NF}' | cut -f 2 -d - | cut -f 1 -d . | head -1`
-    mkdir -p /vm/$DOCKERID
-    VNC="-vnc unix:/vm/$DOCKERID/vnc"
-    echo VNC server will listen on Unix socket /vm/$DOCKERID/vnc
-fi
+# Get all interfaces:
+local_ifaces=($(ip link show | grep -v noop | grep state | grep -v LOOPBACK | awk '{print $2}' | tr -d : | sed 's/@.*$//'))
+local_bridges=($(brctl show | tail -n +2 | awk '{print $1}'))
+# Get non-bridge interfaces:
+for i in "${local_bridges[@]}"
+do
+local_ifaces=(${local_ifaces[@]//*$i*})
+done
 
-exec $LAUNCHER qemu-system-x86_64 -enable-kvm  $VNC `eval echo $KVM_BLK_OPTS` `eval echo $KVM_NET_OPTS` -usbdevice tablet $KVM_ARGS
+DEFAULT_ROUTE=$(ip route | grep default | awk '{print $3}')
+
+configureNetworks
+
+log "INFO" "Launching qemu-kvm"
+log "INFO" "Launching $LAUNCHER $KVM_BLK_OPTS $KVM_OPTS $KVM_CPU_OPTS $KVM_ARGS $@ $KVM_NET_OPTS"
+eval exec $LAUNCHER $KVM_BLK_OPTS $KVM_OPTS $KVM_CPU_OPTS "$@" $KVM_NET_OPTS
